server:
  port: 8080

spring:
  config:
    activate:
      on-profile:
        - local
  datasource:
    url: jdbc:log4jdbc:mysql://%s:%s/%s
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    username: canal
#    password: canal!@12
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 
    port: 
    password: 

###############################################################################
## logging
###############################################################################
logging:
  level:
    root: info
    com:
      sample:
        project: debug
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: debug
      connection: off
